### PR TITLE
ADCS Protocol

### LINKED ISSUE #6: IHU: Define Protocol ADCS ⇄ IHU

### PR DESCRIPTION
**Pull request by ElijahBryonCraig**
Fixes #6

### CODE REVIEW

**Comment by WattsUp** [comment]
Be sure to export to PDF and increment patch number each commit after you request for reviews
Abstract: ...IHU are communicating...
Update the table of contents before each commit
TOC: remove extra space before table
All byte tables: Need to explain what the bytes are not just list them (first one is command ID...)
All commands: what is returned when the ADCS is read from
1: I²C not I2C nor I₂C
2: Remove extra space before heading
Use Code New Roman when typing numbers for programming
Use Equation editor for typing numbers for not programming (real world numbers)
2: "Data request from the IHU to the ADCS as for telemtry packets"?
Reading from the ADCS after receiving multiple commands reflects the most recent command. Does not depend on if the commands are duplicate nor in quick succession
2.1: Latitude and longitude are signed 32b integers with 100µmin/LSB. Don't explain how latitude and longitude work nor unit conversions, if you want link to [geographic coordinate system](https://en.wikipedia.org/wiki/Geographic_coordinate_system). Consider sending both in one command, I don't think one is every needed without the other
2.1.1 & 2.1.2 Don't need these tables
2.2: For Euler angles, 2¹⁶=2π, Unless specified, there is not an offset to the units (don't need to say 0=0).
2.2 Forgot to increment section heading. Temperature is not only for building a telemetry packet. Temperature is 8b signed integer. Remove note about PWM and current, wrong sections
2.4: Currents are 16b signed integers
2.5: Roll Pitch and Yaw do not need a set ID. They are based off of the flight, like a plane but super high. This section is very confusing. You need to send the data with the command. The orientation command(s) need to fulfill the following cases:
- Point camera at the horizon or some other constant orientation (give roll, pitch, yaw)
- Point camera at a place on Earth (give a latitude and longitude)
- Point camera at an object in space (give [equatorial coordinates](https://en.wikipedia.org/wiki/Equatorial_coordinate_system))
- Aim solar panels at sun (no additional information)
- Aim antenna at ground station on Earth (give a latitude and longitude)
- Stop aiming (let the satellite drift)

3 put a page break before each level 1 heading
3.1: Example case doesn't show all of the data being exchanged. It is example communication not example cases. Add an example of data request. Emulate the example communications in PMIC interface [here](https://github.com/CougsInSpace/CougSat1-Software/blob/master/CougSat1-PMIC/docs/PMICInterface.pdf)

**Comment by WattsUp** [comment]
Abstract: ...IHU are communicating...
2: Don't need to say why IHU requests data, each command explains that
All byte tables: Need to explain what the bytes are not just list them (first one is command ID...)
All commands: what is returned when the ADCS is read from
Use Code New Roman when typing numbers for programming
Use Equation editor for typing numbers for not programming (real world numbers)
Standardize table formatting
If a paragraph is more than a line, indent
2.3: Temperature is used more than just telemetry packet, remove this.
2.3: Add temperature request for each coil driver and the GPS
2.3: When adding each coil... use consistent indices across commands for the same component. (Read temp, coil driver, and coil current for the X Coil all at 0x01)
2.4: Rename to Coil Control Data Request. The PWM is the control signal feeding the coil drivers
2.5: Rename to Coil Current
2.6: Separate each command into its own second level heading
2.6-2.6.3: Where is the data passed in? I only see selector bytes. What does the ADCS return (silence is not assumed to be acknowledgement)
2.6.1: Point what at coordinate? where is the ground station? Units of lat and long?
2.6.2: Units? Is [SIDE] a placeholder or a configuration? 
2.6.3: Is [FACE] a placeholder or a configuration?
2.6.3: Roast the chicken... evenly distributes the received power from the sun, aiding to normalize temperatures. ADCS coils not stabilizers
3: The read address of I²C is the write address with an asserted LSB. 0x0F would read the PMIC
3: Add example communication of an orientation request
3: Reading temperature returns one byte, you show two

You have up to 256 commands, (assuming using the first byte as a command index). Don't group communications together into one command unless they are similar. Shorter communications are quicker (albeit 25µs/byte)

**Comment by WattsUp** [comment]
Fixes #6

**Comment by kennetheversole** [comment]
Is this request still valid?

**Pull request merged**
