### PR TITLE
IFJR Protocol Document

### LINKED ISSUE #7: IHU: Define Protocol IFJR ⇄ IHU

### PR DESCRIPTION
**Pull request by ElijahBryonCraig**
Fixes #7

### CODE REVIEW

**Comment by CodySigvartson** [comment]
I personally am confused by the format of the byte tables

**Comment by CodySigvartson** [comment]
Couple things in response to v1.0.3:
- In 2.4.1 how is a multipacket handled, will there be a header on additional packets or just data? 
- In 2.4.1 I feel like there should be a request from IHU to send N byte binary to it. IFJR should respond saying it is ready to accept/store N bytes of data, then IHU can send.
- In all byte tables, does the 0x00 in the box right below byte offset mean anything? The way I am interpreting the byte table it doesn't mean anything and might be better left blank
- In your example commands, what do the hex values in brackets mean (ie. [0x1F] on the first example)? Is is an address?

**Comment by ElijahBryonCraig** [comment]
@CodySigvartson 
1. We don't need to deal with multipackets, as this is a copy from the IHU SD card to the IFJR SD card. The manner in which the satellite retireves said binary from GND is done completely before. Good catch though, I will clarify.
2. The command in 2.2 will be called before sending the binary, to ensure their is space. This is more of an implementation of the function. I believe this isn't needed.
3. For potentially larger tables, they would denote 0x00, 0x08, 0x10, ... this is used to now what offset you are at. Byte offset + header value = byte in table. PM in slack if this confuses more than assists.
4. They represent the write and read locations for the subsystem.

**Comment by kennetheversole** [comment]
@WattsUp Are you ready to merge this?

**Pull request merged**
